
services:

  #frontend:
  #  build: ./env/Dockerfile_REST
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./target:.
  #  command: [ "java","-jar","/app.jar" ]
  #  links:
  #    - restAPI
  #  depends_on:
  #    - restAPI

  #restAPI:
  #  build: ./env/Dockerfile_REST
  #  ports:
  #    - "8081:8081"
  #  volumes:
  #    - ./target:.
  #  command: ["java","-jar","/app.jar"]
  #  links:
  #    - mongo
  #    - frontend
  #  depends_on:
  #    - mongo

  mongo:
    image: mongo:6.0.21
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  db-data: