package de.th_rosenheim.ro_co.frontend.views.tools;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.avatar.AvatarGroup;
import com.vaadin.flow.component.avatar.AvatarGroup.AvatarGroupItem;
import com.vaadin.flow.component.html.H4;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import jakarta.annotation.security.PermitAll;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Tools")
@Route("tool")
@Menu(order = 2, icon = LineAwesomeIconUrl.TOOLS_SOLID)
@PermitAll
public class ToolsView extends Composite<VerticalLayout> {

    public ToolsView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H4 h4 = new H4();
        HorizontalLayout layoutRow = new HorizontalLayout();
        Icon icon = new Icon();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        Paragraph textMedium = new Paragraph();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        H5 h5 = new H5();
        AvatarGroup avatarGroup = new AvatarGroup();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H4 h42 = new H4();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        Icon icon2 = new Icon();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        Paragraph textMedium2 = new Paragraph();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        H5 h52 = new H5();
        AvatarGroup avatarGroup2 = new AvatarGroup();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        H4 h43 = new H4();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        Icon icon3 = new Icon();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        Paragraph textMedium3 = new Paragraph();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        H5 h53 = new H5();
        AvatarGroup avatarGroup3 = new AvatarGroup();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutColumn2.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        h4.setText("3D-Printer");
        h4.setWidth("max-content");
        layoutRow.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("200px");
        layoutRow.setMinHeight("200px");
        layoutRow.setMaxHeight("200px");
        icon.setIcon("lumo:user");
        //icon.setMinWidth("200px");
        //icon.setMinHeight("200px");
        layoutColumn3.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        textMedium.setText(
                "Unser Labor verfügt über modernste 3D-Drucktechnologie, darunter der Ultimaker S5 für präzisen PLA-Druck, der Formlabs Form 3+ für detailgenaue Harzdrucke und das Desktop Metal Studio System 2 für robuste Metallteile. Damit decken wir alle Anforderungen von Prototypen bis zu industriellen Anwendungen ab.");
        textMedium.setWidth("100%");
        textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutRow2.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        h5.setText("Experts:");
        layoutRow2.setAlignSelf(FlexComponent.Alignment.CENTER, h5);
        h5.setWidth("max-content");
        layoutRow2.setAlignSelf(FlexComponent.Alignment.CENTER, avatarGroup);
        avatarGroup.setWidth("min-content");
        setAvatarGroupSampleData(avatarGroup);
        layoutColumn4.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        h42.setText("Nähmaschienen");
        h42.setWidth("max-content");
        layoutRow3.setWidthFull();
        layoutColumn4.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("200px");
        layoutRow3.setMinHeight("200px");
        layoutRow3.setMaxHeight("200px");
        icon2.setIcon("lumo:user");
        //icon2.setMinWidth("200px");
        //icon2.setMinHeight("200px");
        layoutColumn5.setHeightFull();
        layoutRow3.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("100%");
        layoutColumn5.getStyle().set("flex-grow", "1");
        textMedium2.setText(
                "Unser Labor verfügt über zwei hochwertige Nähmaschinen, die vielseitige Einsatzmöglichkeiten bieten. Mit der Brother Innov-is F400, die für präzise Stiche und kreative Projekte entwickelt wurde, und der Juki TL-2000Qi, die durch ihre Geschwindigkeit und Robustheit überzeugt, sind wir bestens ausgerüstet, um kreative und professionelle Näharbeiten umzusetzen.");
        textMedium2.setWidth("100%");
        textMedium2.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutRow4.setWidthFull();
        layoutColumn5.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        h52.setText("Experts:");
        layoutRow4.setAlignSelf(FlexComponent.Alignment.CENTER, h52);
        h52.setWidth("max-content");
        layoutRow4.setAlignSelf(FlexComponent.Alignment.CENTER, avatarGroup2);
        avatarGroup2.setWidth("min-content");
        setAvatarGroupSampleData(avatarGroup2);
        layoutColumn6.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn6);
        layoutColumn6.setWidth("100%");
        layoutColumn6.getStyle().set("flex-grow", "1");
        h43.setText("Holz-& Metallverarbeitung");
        h43.setWidth("max-content");
        layoutRow5.setWidthFull();
        layoutColumn6.setFlexGrow(1.0, layoutRow5);
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.setHeight("200px");
        layoutRow5.setMinHeight("200px");
        layoutRow5.setMaxHeight("200px");
        icon3.setIcon("lumo:user");
        //icon3.setMinWidth("200px");
        //icon3.setMinHeight("200px");
        layoutColumn7.setHeightFull();
        layoutRow5.setFlexGrow(1.0, layoutColumn7);
        layoutColumn7.setWidth("100%");
        layoutColumn7.getStyle().set("flex-grow", "1");
        textMedium3.setText(
                "Hier habt ihr Platz, um euch mit Holz oder Metall auseinander zu setzen. Ein eigenes Eck mit einer Werkbank. Zudem stehen euch Standbohrmaschine, Bandschleifer, Dekupiersäge und eine große Auswahl an Handwerkzeugen zur verfügung.");
        textMedium3.setWidth("100%");
        textMedium3.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutRow6.setWidthFull();
        layoutColumn7.setFlexGrow(1.0, layoutRow6);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.setWidth("100%");
        layoutRow6.getStyle().set("flex-grow", "1");
        h53.setText("Experts:");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, h53);
        h53.setWidth("max-content");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, avatarGroup3);
        avatarGroup3.setWidth("min-content");
        setAvatarGroupSampleData(avatarGroup3);
        getContent().add(layoutColumn2);
        layoutColumn2.add(h4);
        layoutColumn2.add(layoutRow);
        layoutRow.add(icon);
        layoutRow.add(layoutColumn3);
        layoutColumn3.add(textMedium);
        layoutColumn3.add(layoutRow2);
        layoutRow2.add(h5);
        layoutRow2.add(avatarGroup);
        layoutColumn2.add(layoutColumn4);
        layoutColumn4.add(h42);
        layoutColumn4.add(layoutRow3);
        layoutRow3.add(icon2);
        layoutRow3.add(layoutColumn5);
        layoutColumn5.add(textMedium2);
        layoutColumn5.add(layoutRow4);
        layoutRow4.add(h52);
        layoutRow4.add(avatarGroup2);
        layoutColumn2.add(layoutColumn6);
        layoutColumn6.add(h43);
        layoutColumn6.add(layoutRow5);
        layoutRow5.add(icon3);
        layoutRow5.add(layoutColumn7);
        layoutColumn7.add(textMedium3);
        layoutColumn7.add(layoutRow6);
        layoutRow6.add(h53);
        layoutRow6.add(avatarGroup3);
    }

    private void setAvatarGroupSampleData(AvatarGroup avatarGroup) {
        avatarGroup.add(new AvatarGroupItem("A B"));
        avatarGroup.add(new AvatarGroupItem("C D"));
        avatarGroup.add(new AvatarGroupItem("E F"));
    }
}
