
services:

  mongo:
    image: mongo:6.0.21
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - config_own.env
    volumes:
      - ./src/main/resources/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    env_file:
      - config_own.env

volumes:
  db-data:
