
services:

  mongo:
    image: mongo:6.0.21
    restart: always
    ports:
      - "27017:27017"
    command: mongod --quiet --config /etc/mongod.conf --auth
    environment:
      - MONGO_ROCO_CERT_STRING='CN=RoCoDB,OU=RoCoDB,O=RoCo,L=Rosenheim,ST=BY,C=GE'
    volumes:
      - ./../db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./../db/mongod.conf:/etc/mongod.conf
      - ./../db/out/:/etc/ssl/:ro
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    env_file:
      - config_own.env

volumes:
  db-data:
