#Debug:
#debug=true

# Server:
spring.application.name=ro-co-API
server.port=8080

#Documentation:
springdoc.swagger-ui.path=/api.html

########## MongoDB ##########:
spring.data.mongodb.database=RoCoDB
spring.data.mongodb.port=${MONGO_INITDB_PORT}
spring.data.mongodb.host=${MONGO_INITDB_HOST}
spring.data.mongodb.auto-index-creation= true
# Certificate of the CA that signed the certificate to login at MongoDB
tls.caFile.name=certs/RoCoRootCA.pem
# Client certificate to login at MongoDB
tls.certFile.name=certs/RoCoAPI.pem
# Client name to login at MongoDB, must exactly match the format expected by mongoDB (not the subject of the certificate)
security.x509.user=C=GE,ST=BY,L=Rosenheim,O=RoCo,OU=RoCoAPI,CN=RoCoAPI


########## General Security ##########:
# enforces certiciate validation if true
security.enabled=false
#Access key to local keystore
security.keyPWD=${KEYPASS}


########## JWT Security ##########:
#x508 public key cert using ES512 (Elliptic Curve Cryptography) for JWT signing
security.jwt.public-key=${X508_PUBLIC_KEY}
#PKCS8 private key using ES512 (Elliptic Curve Cryptography) for JWT verification
security.jwt.private-key=${PKCS8_PRIVATE_KEY}
# Expieration of JWT tokens in millisecond
security.jwt.expiration-time=3600000
security.jwt.expiration-refresh-time= 86400000

########## Rest Entpoint TLS Encryption ##########:
# Security:
## SSL using RSA
server.ssl.enabled=false
#security.require-ssl=false
#server.tomcat.remote_ip_header=x-forwarded-for
#server.tomcat.protocol_header=x-forwarded-proto

#server.ssl.key-store=classpath:certs/RoCoTLS.p12
#server.ssl.key-store-password=${STOREPASS}
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=RoCoTLS
#server.ssl.key-password=${KEYPASS}
cors.allowed-origin=${CORS_ORIGIN_ALLOWED}


