# mongod.conf
#systemLog:
#    destination: file
#    path: /var/log/mongodb/mongod.log
#    logAppend: true
net:
    port: 27017
    bindIp: 0.0.0.0
    wireObjectCheck: true
    tls:
        mode: requireTLS
        certificateKeyFile: /etc/ssl/RoCoDB.pem  #certificate and key
        #clusterFile: /etc/ssl/mongodb.pem # membership certificate x509 only for clusterd DB!
        CAFile: /etc/ssl/RoCoRootCA.pem #root CA file for validating certificates
        #clusterAuthX509:
        # attributes: O=MongoDB, OU=MongoDB Server
        allowInvalidCertificates: true #only for self-signed certificates
security:
  authorization: enabled
  clusterAuthMode: x509

